repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [--config=setup.cfg]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: docs/, dataset_scripts/, scripts/, test/
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.1.0
    hooks:
      - id: reorder-python-imports
        exclude: docs/
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
      - id: pyupgrade
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.6
    hooks:
      - id: shellcheck
  - repo: https://github.com/myint/docformatter
    rev: v1.4
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries, '88', --wrap-descriptions, '88']
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: python -m mypy --show-error-codes
        language: system
        pass_filenames: false
